{
 "title": "Squid Proxy",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(squid_info_service,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Service Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "squid_up{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "squid_info_UP_Time{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Squid Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(squid_info_service{instance=~\"$instance\"}) by (Squid_Object_Cache_Version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Cache Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "squid_info_Storage_Mem_capacity{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Swap Cache Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "squid_info_Storage_Swap_capacity{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests/s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(squid_client_http_requests_total{instance=~\"$instance\", job=\"squid_exporter\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Server Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (\n  increase(squid_server_http_errors_total{instance=~\"$instance\", job=\"squid_exporter\"}[$__range]) \n  / \n  clamp_min(increase(squid_server_all_requests_total{instance=~\"$instance\", job=\"squid_exporter\"}[$__range]), 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Client Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (\n  increase(squid_client_http_errors_total{instance=~\"$instance\", job=\"squid_exporter\"}[$__range]) \n  / \n  clamp_min(increase(squid_client_http_requests_total{instance=~\"$instance\", job=\"squid_exporter\"}[$__range]), 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(squid_client_http_hits_total{instance=~\"$instance\", job=\"squid_exporter\"}[$__range]) / increase(squid_client_http_requests_total{instance=~\"$instance\", job=\"squid_exporter\"}[$__range]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Service Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "squid_HTTP_Requests_All_50{instance=~\"$instance\"}",
     "legendFormat": "P50"
    },
    {
     "expr": "squid_HTTP_Requests_All_75{instance=~\"$instance\"}",
     "legendFormat": "P75"
    },
    {
     "expr": "squid_HTTP_Requests_All_90{instance=~\"$instance\"}",
     "legendFormat": "P90"
    },
    {
     "expr": "squid_HTTP_Requests_All_95{instance=~\"$instance\"}",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "DNS Lookup Service Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "squid_DNS_Lookups_50{instance=~\"$instance\"}",
     "legendFormat": "P50"
    },
    {
     "expr": "squid_DNS_Lookups_75{instance=~\"$instance\"}",
     "legendFormat": "P75"
    },
    {
     "expr": "squid_DNS_Lookups_90{instance=~\"$instance\"}",
     "legendFormat": "P90"
    },
    {
     "expr": "squid_DNS_Lookups_95{instance=~\"$instance\"}",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Client Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "increase(squid_client_http_kbytes_in_kbytes_total{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "in"
    },
    {
     "expr": "increase(squid_client_http_kbytes_out_kbytes_total{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Cache Hit Service Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "squid_Cache_Hits_50{instance=~\"$instance\"}",
     "legendFormat": "P50"
    },
    {
     "expr": "squid_Cache_Hits_75{instance=~\"$instance\"}",
     "legendFormat": "P75"
    },
    {
     "expr": "squid_Cache_Hits_90{instance=~\"$instance\"}",
     "legendFormat": "P90"
    },
    {
     "expr": "squid_Cache_Hits_95{instance=~\"$instance\"}",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Cache Near Hit Service Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "squid_Near_Hits_50{instance=~\"$instance\"}",
     "legendFormat": "P50"
    },
    {
     "expr": "squid_Near_Hits_75{instance=~\"$instance\"}",
     "legendFormat": "P75"
    },
    {
     "expr": "squid_Near_Hits_90{instance=~\"$instance\"}",
     "legendFormat": "P90"
    },
    {
     "expr": "squid_Near_Hits_95{instance=~\"$instance\"}",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Cache Miss Service Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "squid_Cache_Misses_50{instance=~\"$instance\"}",
     "legendFormat": "P50"
    },
    {
     "expr": "squid_Cache_Misses_75{instance=~\"$instance\"}",
     "legendFormat": "P75"
    },
    {
     "expr": "squid_Cache_Misses_90{instance=~\"$instance\"}",
     "legendFormat": "P90"
    },
    {
     "expr": "squid_Cache_Misses_95{instance=~\"$instance\"}",
     "legendFormat": "P95"
    }
   ]
  }
 ]
}