# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  external_labels:
    cluster: 'localhost-squid'
    replica: '0'

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "squid_exporter"
    static_configs:
      - targets: ["squid-exporter:9301"]

remote_write:
- url: 'http://thanos-receiver:19291/api/v1/receive'
