# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  external_labels:
    host_ip: '127.0.0.1'

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
        labels:
          host_ip: "127.0.0.1"

  - job_name: "squid_exporter"
    static_configs:
      - targets: ["squid-exporter:9301"]
        labels:
          host_ip: "127.0.0.1"
    relabel_configs:
      - source_labels: [host_ip]
        target_label: instance

remote_write:
- url: 'http://thanos-receiver:19291/api/v1/receive'
